---
PROBLEM_SETNAME: "C1_ABI_10"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C1_ABI_10"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

---
PROBLEM_SETNAME: "C1_POL_10"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C1_POL_10"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

---
PROBLEM_SETNAME: "C1_ATL_10"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C1_ATL_10"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

# ---
# PROBLEM_SETNAME: "C1_COS_30"
# SOLVER: "GREEDY"
# TIMELIMIT: null
# LOGPATH: "./data/logs"
# NDIGITS: 5
# ...
# ---
# PROBLEM_SETNAME: "C1_COS_30"
# SOLVER: "ILP@GUROBI"
# TIMELIMIT: null
# LOGPATH: "./data/logs"
# NDIGITS: 5
# ...

# ---
# PROBLEM_SETNAME: "C1_PIO_30"
# SOLVER: "GREEDY"
# TIMELIMIT: null
# LOGPATH: "./data/logs"
# NDIGITS: 5
# ...
# ---
# PROBLEM_SETNAME: "C1_PIO_30"
# SOLVER: "ILP@GUROBI"
# TIMELIMIT: null
# LOGPATH: "./data/logs"
# NDIGITS: 5
# ...