---
PROBLEM_SETNAME: "C3_ABI_10"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C3_ABI_10"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

---
PROBLEM_SETNAME: "C3_POL_10"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C3_POL_10"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

---
PROBLEM_SETNAME: "C3_ATL_10"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C3_ATL_10"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

---
PROBLEM_SETNAME: "C3_COS_30"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C3_COS_30"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...

---
PROBLEM_SETNAME: "C3_PIO_30"
SOLVER: "GREEDY"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...
---
PROBLEM_SETNAME: "C3_PIO_30"
SOLVER: "ILP@GUROBI"
TIMELIMIT: null
LOGPATH: "./data/logs"
NDIGITS: 5
...