---
PROBLEM_SETNAME: "C123_PIO_20"
SAVE_REWARDS: 1
LIVEVIEW: 1
VERBOSE: 1
DELETE_OLD_DATA: 1
N_EPISODES: 500
ALPHA: 0.09  #0.009
GAMMA: 0.2 #0.8
EPSILON_START: 1
EPSILON_END: 0.01 # 0.01
EPSILON_DECAY: 0.99
...